version: '2.1' #Was 2.1 on example
services:
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    ports:
      - "5000:5000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: mysql:8.0
    ports:
      - "32000:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./dbdata:/docker-entrypoint-initdb.d/:ro
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 10s
      timeout: 10s
      retries: 10
